FROM python:3.11-slim

# Unbuffered Python output to see logs live
ENV PYTHONUNBUFFERED=1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Run the Worker Bot
CMD ["python", "zpt_worker.py"]